import { Inter } from "next/font/google"
import "./globals.css"
import Header from "@/components/header/header"

const geistSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
})

const geistMono = Inter({
  variable: "--font-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
