import AntiDiabeticImage from "@/assets/images/AntiDiabetic.png"
import OncologyImage from "@/assets/images/Oncology.png"
import AntibioticsImage from "@/assets/images/Antibiotics.png"
import AntiHypertensiveImage from "@/assets/images/AntiHypertensive.png"
import BetaLactumImage from "@/assets/images/BetaLactum.png"
import NutraceuticalsImage from "@/assets/images/Nutraceuticals.png"
import CardiovascularImage from "@/assets/images/Cardiovascular.png"
import AntiBacterialImage from "@/assets/images/AntiBacterial.png"
import AntiUlcerImage from "@/assets/images/AntiUlcer.png"
import AntiFungalImage from "@/assets/images/AntiFungal.png"
import AntiAllergicImage from "@/assets/images/AntiAllergic.png"
// import TrypsinChymotrypsinTabletsImage from "@/assets/images/TrypsinChymotrypsinTablets.png"
import ParacetamolandCaffeineCapsulesImage from "@/assets/images/ParacetamolandCaffeineCapsules.png"
import CalciumCarbonateTabletsUSPImage from "@/assets/images/CalciumCarbonateTabletsUSP.png"

export const productCategories = [
  {
    title: "Anti Diabetic",
    slug: "anti-diabetic",
    bannerImages: [AntiDiabeticImage],
    products: [
      {
        id: 1,
        name: "Glibenclamide Tablets BP",
        strength: "5 mg",
        form: "Tablets",
      },
      {
        id: 2,
        name: "Gliclazide Modified Release Tablets",
        strength: "30 mg, 60 mg",
        form: "Modified Release Tablets",
      },
      {
        id: 3,
        name: "Gliclazide Tablets BP",
        strength: "40 mg, 80 mg",
        form: "Tablets",
      },
      {
        id: 4,
        name: "Gliclazide + Metformin Hydrochloride Tablets",
        strength: "80 mg + 500 mg, 30 mg + 500 mg",
        form: "Tablets",
      },
      {
        id: 5,
        name: "Glimepiride Tablets",
        strength: "1 mg, 2 mg, 4 mg",
        form: "Tablets",
      },
      { id: 6, name: "Glucose Tablets", strength: "3.4 gm", form: "Tablets" },
      {
        id: 7,
        name: "Pioglitazone Hydrochloride Tablets",
        strength: "15 mg, 30 mg",
        form: "Tablets",
      },
      {
        id: 8,
        name: "Dapagliflozin Tablets",
        strength: "10 mg",
        form: "Tablets",
      },
      {
        id: 9,
        name: "Dapagliflozin Tablets",
        strength: "5 mg",
        form: "Tablets",
      },
      {
        id: 10,
        name: "Empagliflozin Tablets",
        strength: "4 mg",
        form: "Tablets",
      },
      {
        id: 11,
        name: "Empagliflozin Tablets",
        strength: "25 mg",
        form: "Tablets",
      },
      {
        id: 12,
        name: "Glipizide Tablets BP",
        strength: "5 mg",
        form: "Tablets",
      },
      {
        id: 13,
        name: "Metformin Hydrochloride Extended Release Tablets USP",
        strength: "500 mg",
        form: "Tablets",
      },
      {
        id: 14,
        name: "Glimepiride Tablets USP",
        strength: "4 mg",
        form: "Tablets",
      },
      {
        id: 15,
        name: "Vildagliptin + Metformin HCL SR Tablets",
        strength: "50 mg + 1000 mg",
        form: "Tablets",
      },
      {
        id: 16,
        name: "Canagliflozin Tablets",
        strength: "100 mg",
        form: "Tablets",
      },
      {
        id: 17,
        name: "Glimepiride + Metformin HCL Tablets",
        strength: "N/A",
        form: "Tablets",
      },
      {
        id: 18,
        name: "Sitagliptin Phosphate + Metformin Hydrochloride Tablets",
        strength: "50 mg + 1000 mg",
        form: "Tablets",
      },
    ],
  },
  {
    title: "Oncology",
    slug: "oncology",
    bannerImages: [OncologyImage],
    products: [
      {
        id: 1,
        name: "Imatinib Tablets",
        strength: "100 mg, 400 mg",
        form: "Tablets",
      },
      {
        id: 2,
        name: "Capecitabine Tablets",
        strength: "500 mg",
        form: "Tablets",
      },
    ],
  },
  {
    title: "Antibiotics",
    slug: "antibiotics",
    bannerImages: [AntibioticsImage],
    products: [
      {
        id: 1,
        name: "Amoxicillin Capsules",
        strength: "250 mg, 500 mg",
        form: "Capsules",
      },
      {
        id: 2,
        name: "Azithromycin Tablets",
        strength: "250 mg, 500 mg",
        form: "Tablets",
      },
    ],
  },
  {
    title: "Anti Hypertensive",
    slug: "anti-hypertensive",
    bannerImages: [AntiHypertensiveImage],
    products: [
      {
        id: 1,
        name: "Amlodipine Tablets",
        strength: "5 mg, 10 mg",
        form: "Tablets",
      },
      {
        id: 2,
        name: "Losartan Tablets",
        strength: "25 mg, 50 mg",
        form: "Tablets",
      },
    ],
  },
  {
    title: "Beta Lactum",
    slug: "beta-lactum",
    bannerImages: [BetaLactumImage],
    products: [
      {
        id: 1,
        name: "Cefixime Tablets",
        strength: "200 mg",
        form: "Tablets",
      },
      {
        id: 2,
        name: "Ceftriaxone Injection",
        strength: "1 gm",
        form: "Injection",
      },
    ],
  },
  {
    title: "Nutraceuticals",
    slug: "nutraceuticals",
    bannerImages: [NutraceuticalsImage],
    products: [
      {
        id: 1,
        name: "Multivitamin Tablets",
        strength: "N/A",
        form: "Tablets",
      },
      {
        id: 2,
        name: "Calcium + Vitamin D3",
        strength: "500 mg + 200 IU",
        form: "Tablets",
      },
    ],
  },

  {
    title: "Cardiovascular",
    slug: "cardiovascular",
    bannerImages: [CardiovascularImage],
    products: [
      {
        id: 1,
        name: "Lisinopril Tablets USP",
        strength: "5 mg, 10 mg, 20 mg",
        form: "Tablets",
      },
      {
        id: 2,
        name: "Losartan Potassium Tablets",
        strength: "25 mg, 50 mg",
        form: "Tablets",
      },
      {
        id: 3,
        name: "Losartan Potassium + Hydrochlorothiazide Tablets USP",
        strength: "50 mg + 12.5 mg",
        form: "Tablets",
      },
      {
        id: 4,
        name: "Propranolol Tablets BP",
        strength: "10 mg, 40 mg",
        form: "Tablets",
      },
      {
        id: 5,
        name: "Ramipril Tablets",
        strength: "1.25 mg, 2.5 mg, 5 mg, 10 mg",
        form: "Tablets",
      },
      {
        id: 6,
        name: "Ramipril + Hydrochlorothiazide Tablets",
        strength: "2.5 mg + 12.5 mg",
        form: "Tablets",
      },
      {
        id: 7,
        name: "Rosuvastatin Calcium Tablets",
        strength: "5 mg, 10 mg, 20 mg",
        form: "Tablets",
      },
      {
        id: 8,
        name: "Simvastatin Tablets USP",
        strength: "10 mg, 20 mg, 40 mg, 80 mg",
        form: "Tablets",
      },
      {
        id: 9,
        name: "Spironolactone Tablets",
        strength: "25 mg, 50 mg, 100 mg",
        form: "Tablets",
      },
      {
        id: 10,
        name: "Trimetazidine Hydrochloride Tablets",
        strength: "20 mg",
        form: "Tablets",
      },
      {
        id: 11,
        name: "Furosemide Tablets BP",
        strength: "40 mg",
        form: "Tablets",
      },
      {
        id: 12,
        name: "Hydralazine Tablets BP",
        strength: "25 mg",
        form: "Tablets",
      },
      {
        id: 13,
        name: "Hydrochlorothiazide Tablets BP",
        strength: "25 mg, 50 mg",
        form: "Tablets",
      },
      {
        id: 14,
        name: "Indapamide Tablets USP",
        strength: "2.5 mg",
        form: "Tablets",
      },
      {
        id: 15,
        name: "Indapamide Sustained Release Tablets",
        strength: "1.5 mg",
        form: "Tablets",
      },
      {
        id: 16,
        name: "Methyldopa Tablets BP",
        strength: "250 mg",
        form: "Tablets",
      },
      { id: 17, name: "Prazosin Tablets", strength: "5 mg", form: "Tablets" },
      {
        id: 18,
        name: "Telmisartan Tablets",
        strength: "20 mg, 40 mg, 80 mg",
        form: "Tablets",
      },
      {
        id: 19,
        name: "Terazosin Hydrochloride Tablets",
        strength: "1 mg, 2 mg",
        form: "Tablets",
      },
      {
        id: 20,
        name: "Valsartan Tablets",
        strength: "80 mg, 160 mg",
        form: "Tablets",
      },
      {
        id: 21,
        name: "Verapamil Tablets BP",
        strength: "40 mg",
        form: "Tablets",
      },
      {
        id: 22,
        name: "Prolonged Release Verapamil Tablets",
        strength: "120 mg",
        form: "Tablets",
      },
      {
        id: 23,
        name: "Amiodarone Tablets BP",
        strength: "200 mg",
        form: "Tablets",
      },
      {
        id: 24,
        name: "Amlodipine Tablets",
        strength: "5 mg, 10 mg",
        form: "Tablets",
      },
      {
        id: 25,
        name: "S-Amlodipine Tablets",
        strength: "5 mg",
        form: "Tablets",
      },
      {
        id: 26,
        name: "Amlodipine + Lisinopril Tablets",
        strength: "5 mg + 5 mg, 10 mg + 10 mg",
        form: "Tablets",
      },
      {
        id: 27,
        name: "Amlodipine + Telmisartan Tablets",
        strength: "5 mg + 40 mg",
        form: "Tablets",
      },
      {
        id: 28,
        name: "Amlodipine + Atenolol Tablets",
        strength: "5 mg + 50 mg",
        form: "Tablets",
      },
      {
        id: 29,
        name: "Amlodipine + Hydrochlorothiazide Tablets",
        strength: "5 mg + 12.5 mg, 2.5 mg + 12.5 mg",
        form: "Tablets",
      },
      {
        id: 30,
        name: "Atenolol Tablets BP",
        strength: "50 mg, 100 mg",
        form: "Tablets",
      },
      {
        id: 31,
        name: "Atorvastatin Tablets",
        strength: "10 mg, 20 mg, 40 mg, 80 mg",
        form: "Tablets",
      },
      {
        id: 32,
        name: "Co-Amilozide Tablets BP",
        strength: "5 mg + 50 mg",
        form: "Tablets",
      },
      {
        id: 33,
        name: "Carvedilol Tablets USP",
        strength: "6.25 mg, 12.5 mg, 25 mg",
        form: "Tablets",
      },
      {
        id: 34,
        name: "Captopril Tablets USP",
        strength: "25 mg, 50 mg",
        form: "Tablets",
      },
      {
        id: 35,
        name: "Amlodipine Besylate Tablets USP",
        strength: "5 mg",
        form: "Tablets",
      },
      {
        id: 36,
        name: "Rosuvastatin Tablets",
        strength: "10 mg",
        form: "Tablets",
      },
      {
        id: 37,
        name: "Trimetazidine Hydrochloride MR Tablets",
        strength: "80 mg",
        form: "Tablets",
      },
      {
        id: 38,
        name: "Telmisartan + Amlodipine Tablets",
        strength: "N/A",
        form: "Tablets",
      },
      {
        id: 39,
        name: "Losartan Potassium Tablets USP",
        strength: "50 mg",
        form: "Tablets",
      },
      {
        id: 40,
        name: "Telmisartan Tablets USP",
        strength: "40 mg",
        form: "Tablets",
      },
      {
        id: 41,
        name: "Ticagrelor Tablets BP",
        strength: "90 mg",
        form: "Tablets",
      },
      {
        id: 42,
        name: "Sacubitril + Valsartan Tablets",
        strength: "97 mg + 103 mg",
        form: "Tablets",
      },
    ],
  },
  {
    title: "Anti Bacterial",
    slug: "anti-bacterial",
    bannerImages: [AntiBacterialImage],
    products: [
      {
        id: 1,
        name: "Cefpodoxime Proxetil Oral Suspension USP",
        strength: "50 mg, 100 mg",
        form: "Oral Suspension",
      },
      {
        id: 2,
        name: "Cefixime Tablets USP",
        strength: "100 mg, 200 mg, 400 mg",
        form: "Tablets",
      },
      {
        id: 3,
        name: "Cefixime Dispersible Tablets",
        strength: "100 mg, 400 mg",
        form: "Dispersible Tablets",
      },
      {
        id: 4,
        name: "Cefixime Granules",
        strength: "100 mg",
        form: "Granules",
      },
      {
        id: 5,
        name: "Cefixime + Lactobacillus Granules",
        strength: "100 mg + 400 million spores",
        form: "Granules",
      },
      {
        id: 6,
        name: "Cefixime Oral Suspension USP",
        strength: "50 mg",
        form: "Oral Suspension",
      },
      {
        id: 7,
        name: "Cefuroxime Axetil Tablets USP",
        strength: "250 mg, 500 mg",
        form: "Tablets",
      },
      {
        id: 8,
        name: "Cefuroxime Axetil Oral Suspension USP",
        strength: "125 mg",
        form: "Oral Suspension",
      },
      {
        id: 9,
        name: "Cefdinir Capsules USP",
        strength: "300 mg",
        form: "Capsules",
      },
      {
        id: 10,
        name: "Cefdinir Dispersible Tablets",
        strength: "150 mg, 300 mg",
        form: "Tablets",
      },
      {
        id: 11,
        name: "Cefradine Capsules BP",
        strength: "500 mg",
        form: "Capsules",
      },
      {
        id: 12,
        name: "Clarithromycin Tablets BP",
        strength: "250 mg, 500 mg",
        form: "Tablets",
      },
      {
        id: 13,
        name: "Clarithromycin Oral Suspension BP",
        strength: "125 mg",
        form: "Oral Suspension",
      },
      {
        id: 14,
        name: "Clindamycin Capsules BP",
        strength: "150 mg",
        form: "Capsules",
      },
      {
        id: 15,
        name: "Cloxacillin Sodium Capsules",
        strength: "250 mg, 500 mg",
        form: "Capsules",
      },
      {
        id: 16,
        name: "Erythromycin Stearate Tablets BP",
        strength: "250 mg, 500 mg",
        form: "Tablets",
      },
      {
        id: 17,
        name: "Erythromycin Estolate Tablets USP",
        strength: "500 mg",
        form: "Tablets",
      },
      {
        id: 18,
        name: "Erythromycin Ethyl Succinate Oral Suspension BP",
        strength: "125 mg",
        form: "Suspension",
      },
      {
        id: 19,
        name: "Flucloxacillin Capsules BP",
        strength: "500 mg",
        form: "Capsules",
      },
      {
        id: 20,
        name: "Gemifloxacin Tablets",
        strength: "320 mg",
        form: "Tablets",
      },
      {
        id: 21,
        name: "Roxithromycin Tablets",
        strength: "150 mg, 300 mg",
        form: "Tablets",
      },
      {
        id: 22,
        name: "Tinidazole + Miconazole Nitrate + Neomycin Vaginal Tablets",
        strength: "500 mg + 100 mg + 20 mg",
        form: "Tablets",
      },
      {
        id: 23,
        name: "Cloxacillin Oral Suspension USP",
        strength: "125 mg",
        form: "Oral Suspension",
      },
      {
        id: 24,
        name: "Doxycycline Capsules USP",
        strength: "100 mg",
        form: "Capsules",
      },
      {
        id: 25,
        name: "Doxycycline Hyclate Tablets",
        strength: "100 mg",
        form: "Tablets",
      },
      {
        id: 26,
        name: "Amoxicillin Capsules BP",
        strength: "250 mg, 500 mg",
        form: "Capsules",
      },
      {
        id: 27,
        name: "Amoxicillin Tablets",
        strength: "1 gm",
        form: "Tablets",
      },
      {
        id: 28,
        name: "Co-Amoxiclav Oral Suspension BP",
        strength: "125 mg + 31.25 mg",
        form: "Oral Suspension",
      },
      {
        id: 29,
        name: "Co-Amoxiclav Tablets BP",
        strength: "250 mg + 125 mg, 500 mg + 125 mg, 875 mg + 125 mg",
        form: "Tablets",
      },
      {
        id: 30,
        name: "Amoxicillin + Clavulanate Potassium Oral Suspension USP",
        strength: "200 mg + 28.5 mg",
        form: "Oral Suspension",
      },
      {
        id: 31,
        name: "Amoxicillin Oral Suspension BP",
        strength: "250 mg",
        form: "Oral Suspension",
      },
      {
        id: 32,
        name: "Amoxicillin + Cloxacillin Capsules",
        strength: "250 mg + 250 mg",
        form: "Capsules",
      },
      {
        id: 33,
        name: "Cefadroxil Tablets USP",
        strength: "500 mg",
        form: "Tablets",
      },
      {
        id: 34,
        name: "Cefadroxil Dispersible Tablets",
        strength: "250 mg",
        form: "Tablets",
      },
      {
        id: 35,
        name: "Cefadroxil Capsules USP",
        strength: "500 mg",
        form: "Capsules",
      },
      {
        id: 36,
        name: "Cefadroxil Oral Suspension BP",
        strength: "125 mg, 250 mg",
        form: "Oral Suspension",
      },
      {
        id: 37,
        name: "Cefpodoxime Proxetil Dispersible Tablets",
        strength: "100 mg",
        form: "Dispersible Tablets",
      },
      {
        id: 38,
        name: "Cefpodoxime Proxetil Tablets USP",
        strength: "100 mg, 200 mg",
        form: "Tablets",
      },
      {
        id: 39,
        name: "Cefpodoxime Proxetil Granules",
        strength: "100 mg",
        form: "Granules",
      },
      {
        id: 40,
        name: "Levofloxacin Tablets",
        strength: "250 mg, 500 mg, 750 mg",
        form: "Tablets",
      },
      {
        id: 41,
        name: "Metronidazole Oral Suspension BP",
        strength: "200 mg",
        form: "Oral Suspension",
      },
      {
        id: 42,
        name: "Metronidazole Tablets BP",
        strength: "200 mg, 250 mg",
        form: "Tablets",
      },
      {
        id: 43,
        name: "Metronidazole + Furazolidone Tablets",
        strength: "1 gm + 200 mg",
        form: "Tablets",
      },
      {
        id: 44,
        name: "Moxifloxacin Tablets",
        strength: "400 mg",
        form: "Tablets",
      },
      {
        id: 45,
        name: "Norfloxacin Tablets BP",
        strength: "400 mg",
        form: "Tablets",
      },
      {
        id: 46,
        name: "Norfloxacin + Metronidazole Tablets",
        strength: "400 mg + 250 mg",
        form: "Tablets",
      },
      {
        id: 47,
        name: "Norfloxacin + Tinidazole Tablets",
        strength: "400 mg + 600 mg",
        form: "Tablets",
      },
      {
        id: 48,
        name: "Ofloxacin Tablets",
        strength: "200 mg, 400 mg",
        form: "Tablets",
      },
      {
        id: 49,
        name: "Ofloxacin + Ornidazole Tablets",
        strength: "200 mg + 500 mg",
        form: "Tablets",
      },
      {
        id: 50,
        name: "Ornidazole Tablets",
        strength: "500 mg",
        form: "Tablets",
      },
      {
        id: 51,
        name: "Pefloxacin Tablets",
        strength: "400 mg",
        form: "Tablets",
      },
      {
        id: 52,
        name: "Tetracycline Capsules BP",
        strength: "250 mg, 500 mg",
        form: "Capsules",
      },
      {
        id: 53,
        name: "Sparfloxacin Tablets",
        strength: "100 mg, 200 mg",
        form: "Tablets",
      },
      {
        id: 54,
        name: "Ciprofloxacin Tablets USP",
        strength: "250 mg, 500 mg",
        form: "Tablets",
      },
      {
        id: 55,
        name: "Ciprofloxacin + Tinidazole Tablets",
        strength: "500 mg + 600 mg",
        form: "Tablets",
      },
      {
        id: 56,
        name: "Ciprofloxacin Extended Release Tablets",
        strength: "500 mg, 1 gm",
        form: "Tablets",
      },
      {
        id: 57,
        name: "Chloramphenicol Capsules BP",
        strength: "250 mg",
        form: "Capsules",
      },
      {
        id: 58,
        name: "Abacavir Sulphate Tablets",
        strength: "300 mg",
        form: "Tablets",
      },
      {
        id: 59,
        name: "Artemether + Lumefantrine Oral Suspension",
        strength: "180 mg + 1080 mg",
        form: "Suspension",
      },
      {
        id: 60,
        name: "Artemether + Lumefantrine Tablets",
        strength: "20 mg + 120 mg, 40 mg + 240 mg, 80 mg + 480 mg",
        form: "Tablets",
      },
      {
        id: 61,
        name: "Amoxicillin + Clavulanate Injection BP",
        strength: "1.2 gm",
        form: "Injection",
      },
      {
        id: 62,
        name: "Meropenem Injection USP",
        strength: "1 gm",
        form: "Injection",
      },
      {
        id: 63,
        name: "Ondansetron ODT USP",
        strength: "4 mg",
        form: "Tablets",
      },
      {
        id: 64,
        name: "Moxifloxacin IV Infusion",
        strength: "0.4% w/v",
        form: "Infusion",
      },
      {
        id: 65,
        name: "Amoxicillin + Clavulanate Tablets USP",
        strength: "375 mg",
        form: "Tablets",
      },
      {
        id: 66,
        name: "Metronidazole IV Infusion BP",
        strength: "0.5% w/v",
        form: "Infusion",
      },
      {
        id: 67,
        name: "Levofloxacin Infusion",
        strength: "500 mg / 100 ml",
        form: "Infusion",
      },
      {
        id: 68,
        name: "Azithromycin Dispersible Tablets",
        strength: "500 mg",
        form: "Tablets",
      },
    ],
  },
  {
    title: "Anti Ulcer",
    slug: "anti-ulcer",
    bannerImages: [AntiUlcerImage],
    products: [
      {
        id: 1,
        name: "Lansoprazole Capsules",
        strength: "15 mg, 30 mg",
        form: "Capsules",
      },
      {
        id: 2,
        name: "Lansoprazole Delayed Release Capsules USP",
        strength: "30 mg",
        form: "Capsules",
      },
      {
        id: 3,
        name: "Misoprostol Tablets",
        strength: "200 mg",
        form: "Tablets",
      },
      {
        id: 4,
        name: "Omeprazole Capsules",
        strength: "20 mg, 40 mg",
        form: "Capsules",
      },
      {
        id: 5,
        name: "Omeprazole Delayed Release Capsules USP",
        strength: "20 mg",
        form: "Capsules",
      },
      {
        id: 6,
        name: "Omeprazole + Domperidone Capsules",
        strength: "20 mg + 10 mg",
        form: "Capsules",
      },
      {
        id: 7,
        name: "Propantheline Tablets BP",
        strength: "15 mg",
        form: "Tablets",
      },
      {
        id: 8,
        name: "Rabeprazole Tablets",
        strength: "10 mg, 20 mg",
        form: "Tablets",
      },
      {
        id: 9,
        name: "Rabeprazole Sodium Tablets",
        strength: "20 mg",
        form: "Tablets",
      },
      {
        id: 10,
        name: "Omeprazole + Tinidazole + Clarithromycin Combipack",
        strength: "20 mg + 500 mg + 250 mg",
        form: "Tablets",
      },
      {
        id: 11,
        name: "Esomeprazole Capsules",
        strength: "40 mg",
        form: "Capsules",
      },
      {
        id: 12,
        name: "Rabeprazole Sodium Injection",
        strength: "20 mg",
        form: "Injection",
      },
      {
        id: 13,
        name: "Rabeprazole Capsules",
        strength: "20 mg",
        form: "Capsules",
      },
      {
        id: 14,
        name: "Pantoprazole Injection BP",
        strength: "40 mg",
        form: "Injection",
      },
      {
        id: 15,
        name: "Pantoprazole Sodium Tablets",
        strength: "40 mg",
        form: "Tablets",
      },
      {
        id: 16,
        name: "Gastro-Resistant Omeprazole Capsules BP",
        strength: "20 mg",
        form: "Capsules",
      },
      {
        id: 17,
        name: "Gastro-Resistant Omeprazole Capsules BP",
        strength: "20 mg",
        form: "Capsules",
      },
      {
        id: 18,
        name: "Alumina + Magnesia + Simethicone Chewable Tablets USP",
        strength: "250 mg + 250 mg + 50 mg",
        form: "Tablets",
      },
      {
        id: 19,
        name: "Gastro-Resistant Diclofenac Tablets BP",
        strength: "50 mg",
        form: "Tablets",
      },
      {
        id: 20,
        name: "Esomeprazole Tablets",
        strength: "20 mg",
        form: "Tablets",
      },
      {
        id: 21,
        name: "Ondansetron Injection BP",
        strength: "4 ml",
        form: "Injection",
      },
      {
        id: 22,
        name: "Omeprazole Injection",
        strength: "40 mg",
        form: "Injection",
      },
      {
        id: 23,
        name: "Digestive Enzyme Syrup",
        strength: "100 ml",
        form: "Syrup",
      },
      {
        id: 24,
        name: "Gastro-Resistant Bisacodyl Tablets BP",
        strength: "5 mg",
        form: "Tablets",
      },
    ],
  },
  {
    title: "Anti Fungal",
    slug: "anti-fungal",
    bannerImages: [AntiFungalImage],
    products: [
      {
        id: 1,
        name: "Ampicillin Capsules BP",
        strength: "250 mg, 500 mg",
        form: "Capsules",
      },
      {
        id: 2,
        name: "Azithromycin Tablets",
        strength: "250 mg, 500 mg",
        form: "Tablets",
      },
      {
        id: 3,
        name: "Azithromycin Oral Suspension USP",
        strength: "200 mg",
        form: "Oral Suspension",
      },
      {
        id: 4,
        name: "Cephalexin Capsules BP",
        strength: "250 mg, 500 mg",
        form: "Capsules",
      },
      {
        id: 5,
        name: "Cefalexin Tablets BP",
        strength: "1 gm",
        form: "Tablets",
      },
      {
        id: 6,
        name: "Griseofulvin Tablets BP",
        strength: "500 mg",
        form: "Tablets",
      },
      {
        id: 7,
        name: "Itraconazole Capsules",
        strength: "100 mg",
        form: "Capsules",
      },
      {
        id: 8,
        name: "Ketoconazole Tablets USP",
        strength: "200 mg",
        form: "Tablets",
      },
      {
        id: 9,
        name: "Pefloxacin Tablets",
        strength: "400 mg",
        form: "Tablets",
      },
      {
        id: 10,
        name: "Pivmecillinam Hydrochloride Tablets BP",
        strength: "200 mg",
        form: "Tablets",
      },
      {
        id: 11,
        name: "Secnidazole Tablets",
        strength: "500 mg, 1 gm",
        form: "Tablets",
      },
      {
        id: 12,
        name: "Trimethoprim + Sulphamethoxazole Tablets BP",
        strength: "80 mg + 400 mg, 160 mg + 800 mg",
        form: "Tablets",
      },
      {
        id: 13,
        name: "Luliconazole Cream",
        strength: "1% w/w",
        form: "Ointment",
      },
      {
        id: 14,
        name: "Fluconazole Tablets",
        strength: "50 mg, 150 mg",
        form: "Tablets",
      },
      {
        id: 15,
        name: "Fluconazole Capsules",
        strength: "100 mg, 150 mg",
        form: "Capsules",
      },
      {
        id: 16,
        name: "Clotrimazole Vaginal Tablets BP",
        strength: "100 mg",
        form: "Tablets",
      },
      {
        id: 17,
        name: "Clotrimazole Cream USP",
        strength: "1% w/w",
        form: "Cream",
      },
    ],
  },
  {
    title: "Anti Allergic",
    slug: "anti-allergic",
    bannerImages: [AntiAllergicImage],
    products: [
      {
        id: 1,
        name: "Levocetirizine Dihydrochloride Tablets",
        strength: "5 mg, 10 mg",
        form: "Tablets",
      },
      {
        id: 2,
        name: "Loratadine Tablets USP",
        strength: "10 mg",
        form: "Tablets",
      },
      {
        id: 3,
        name: "Loratadine Oral Suspension",
        strength: "5 mg",
        form: "Oral Suspension",
      },
      {
        id: 4,
        name: "Metformin Hydrochloride Tablets",
        strength: "500 mg, 850 mg",
        form: "Tablets",
      },
      {
        id: 5,
        name: "Metformin + Pioglitazone Hydrochloride Tablets",
        strength: "500 mg + 15 mg",
        form: "Tablets",
      },
      {
        id: 6,
        name: "Metformin Sustained Release Tablets",
        strength: "500 mg, 1000 mg",
        form: "Tablets",
      },
      {
        id: 7,
        name: "Metformin Hydrochloride Extended Release Tablets USP",
        strength: "500 mg",
        form: "Tablets",
      },
      {
        id: 8,
        name: "Montelukast Tablets",
        strength: "5 mg, 10 mg",
        form: "Tablets",
      },
      {
        id: 9,
        name: "Paracetamol + Caffeine + Pseudoephedrine HCl + Chlorpheniramine Maleate Tablets",
        strength: "500 mg + 25 mg + 30 mg + 2 mg",
        form: "Tablets",
      },
      {
        id: 10,
        name: "Paracetamol + Caffeine + Chlorpheniramine + Phenylephrine Tablets",
        strength: "500 mg + 30 mg + 2 mg",
        form: "Tablets",
      },
      {
        id: 11,
        name: "Paracetamol + Pseudoephedrine HCl + Chlorpheniramine Maleate Capsules",
        strength: "500 mg + 30 mg + 2 mg",
        form: "Capsules",
      },
      {
        id: 12,
        name: "Paracetamol + Phenylephrine HCl + Chlorpheniramine Maleate Tablets",
        strength: "500 mg + 5 mg + 2 mg",
        form: "Tablets",
      },
      {
        id: 13,
        name: "Paracetamol + Chlorpheniramine Maleate + Caffeine + Phenylephrine Tablets",
        strength: "500 mg + 4 mg + 30 mg + 2.5 mg",
        form: "Tablets",
      },
      {
        id: 14,
        name: "Prednisolone Tablets BP",
        strength: "5 mg, 10 mg, 25 mg",
        form: "Tablets",
      },
      {
        id: 15,
        name: "Promethazine Teoclate Tablets",
        strength: "25 mg",
        form: "Tablets",
      },
      {
        id: 16,
        name: "Triprolidine + Pseudoephedrine Tablets USP",
        strength: "2.5 mg, 60 mg",
        form: "Tablets",
      },
      {
        id: 17,
        name: "Betahistine Dihydrochloride Tablets BP",
        strength: "8 mg",
        form: "Tablets",
      },
      {
        id: 18,
        name: "Bromhexine Hydrochloride Tablets",
        strength: "8 mg",
        form: "Tablets",
      },
      {
        id: 19,
        name: "Cinnarizine Tablets",
        strength: "25 mg",
        form: "Tablets",
      },
      {
        id: 20,
        name: "Cetirizine Tablets",
        strength: "10 mg",
        form: "Tablets",
      },
      {
        id: 21,
        name: "Chlorphenamine Tablets BP",
        strength: "4 mg",
        form: "Tablets",
      },
      {
        id: 22,
        name: "Chlorpromazine Tablets BP",
        strength: "25 mg, 50 mg",
        form: "Tablets",
      },
      {
        id: 23,
        name: "Cyproheptadine Hydrochloride Tablets BP",
        strength: "4 mg",
        form: "Tablets",
      },
      {
        id: 24,
        name: "Dexamethasone Tablets BP",
        strength: "0.5 mg, 2 mg",
        form: "Tablets",
      },
      {
        id: 25,
        name: "Fexofenadine Tablets USP",
        strength: "120 mg, 180 mg",
        form: "Tablets",
      },
      {
        id: 26,
        name: "Hydrocortisone Tablets USP",
        strength: "5 mg, 10 mg, 20 mg",
        form: "Tablets",
      },
    ],
  },
  {
    title: "Pain Management",
    slug: "pain-management",
    bannerImages: [ParacetamolandCaffeineCapsulesImage],
    products: [
      {
        id: 1,
        name: "Trypsin + Chymotrypsin Tablets",
        strength: "50000 IU + 100000 IU",
        form: "Tablets",
      },
      {
        id: 2,
        name: "Flunarizine Tablets",
        strength: "5 mg, 10 mg",
        form: "Tablets",
      },
      {
        id: 3,
        name: "Glucosamine Sulphate Tablets",
        strength: "500 mg, 750 mg",
        form: "Tablets",
      },
      {
        id: 4,
        name: "Glucosamine + Chondroitin Sulphate Tablets",
        strength: "250 mg + 250 mg",
        form: "Tablets",
      },
      {
        id: 5,
        name: "Hydroxychloroquine Sulfate Tablets USP",
        strength: "200 mg",
        form: "Tablets",
      },
      {
        id: 6,
        name: "Hyoscine Butyl Bromide Tablets BP",
        strength: "10 mg",
        form: "Tablets",
      },
      {
        id: 7,
        name: "Ibuprofen Tablets BP",
        strength: "200 mg, 400 mg, 800 mg",
        form: "Tablets",
      },
      {
        id: 8,
        name: "Ibuprofen Capsules",
        strength: "400 mg",
        form: "Capsules",
      },
      {
        id: 9,
        name: "Ibuprofen + Paracetamol Tablets",
        strength: "400 mg + 325 mg",
        form: "Tablets",
      },
      {
        id: 10,
        name: "Indomethacin Capsules USP",
        strength: "25 mg",
        form: "Capsules",
      },
      {
        id: 11,
        name: "Orphenadrine Citrate + Paracetamol Tablets",
        strength: "35 mg + 450 mg",
        form: "Tablets",
      },
      {
        id: 12,
        name: "Orphenadrine Citrate Tablets",
        strength: "100 mg",
        form: "Tablets",
      },
      {
        id: 13,
        name: "Paracetamol Tablets BP",
        strength: "250 mg, 500 mg",
        form: "Tablets",
      },
      {
        id: 14,
        name: "Paracetamol + Caffeine Tablets",
        strength: "600 mg + 50 mg, 500 mg + 50 mg",
        form: "Tablets",
      },
      {
        id: 15,
        name: "Paracetamol + Caffeine Capsules",
        strength: "500 mg + 30 mg",
        form: "Capsules",
      },
      {
        id: 16,
        name: "Paracetamol + Dicyclomine Hydrochloride Tablets",
        strength: "500 mg + 20 mg",
        form: "Tablets",
      },
      {
        id: 17,
        name: "Paracetamol + Diclofenac Sodium Tablets",
        strength: "500 mg + 50 mg",
        form: "Tablets",
      },
      {
        id: 18,
        name: "Paracetamol + Ibuprofen + Caffeine Capsules",
        strength: "325 mg + 200 mg + 40 mg",
        form: "Capsules",
      },
      {
        id: 19,
        name: "Paracetamol + Ibuprofen + Caffeine Capsules",
        strength: "325 mg + 200 mg + 30 mg",
        form: "Capsules",
      },
      {
        id: 20,
        name: "Paracetamol + Ibuprofen Tablets",
        strength: "500 mg + 400 mg",
        form: "Tablets",
      },
      {
        id: 21,
        name: "Paracetamol + Tramadol Tablets",
        strength: "500 mg + 50 mg",
        form: "Tablets",
      },
      {
        id: 22,
        name: "Pentazocine Capsules BP",
        strength: "25 mg",
        form: "Capsules",
      },
      {
        id: 23,
        name: "Pregabalin Capsules",
        strength: "75 mg, 150 mg",
        form: "Capsules",
      },
      {
        id: 24,
        name: "Piroxicam Capsules BP",
        strength: "20 mg",
        form: "Capsules",
      },
      {
        id: 25,
        name: "Tizanidine Tablets USP",
        strength: "2 mg",
        form: "Tablets",
      },
      {
        id: 26,
        name: "Tramadol Tablets",
        strength: "50 mg, 100 mg, 200 mg",
        form: "Tablets",
      },
      {
        id: 27,
        name: "Tramadol Capsules BP",
        strength: "50 mg, 100 mg",
        form: "Capsules",
      },
      {
        id: 28,
        name: "Trypsin + Chymotrypsin + Diclofenac Potassium",
        strength: "50000 IU + 50 mg",
        form: "Tablets",
      },
      {
        id: 29,
        name: "Aceclofenac Tablets BP",
        strength: "100 mg",
        form: "Tablets",
      },
      {
        id: 30,
        name: "Aceclofenac + Paracetamol Tablets BP",
        strength: "100 mg + 500 mg",
        form: "Tablets",
      },
      {
        id: 31,
        name: "Diclofenac Potassium Tablets",
        strength: "50 mg",
        form: "Tablets",
      },
      {
        id: 32,
        name: "Diclofenac Sodium Tablets",
        strength: "50 mg, 100 mg",
        form: "Tablets",
      },
      {
        id: 33,
        name: "Baclofen Tablets USP",
        strength: "10 mg",
        form: "Tablets",
      },
      {
        id: 34,
        name: "Diclofenac Potassium Sustained Release Tablets",
        strength: "100 mg",
        form: "Tablets",
      },
      {
        id: 35,
        name: "Diclofenac Potassium + Chlorzoxazone + Paracetamol Tablets",
        strength: "50 mg + 250 mg + 500 mg",
        form: "Tablets",
      },
      {
        id: 36,
        name: "Diclofenac Sodium Capsules",
        strength: "50 mg",
        form: "Capsules",
      },
      {
        id: 37,
        name: "Diclofenac Prolonged Release Tablets BP",
        strength: "100 mg",
        form: "Tablets",
      },
      {
        id: 38,
        name: "Aceclofenac + Paracetamol + Serratiopeptidase Tablets",
        strength: "100 mg + 500 mg + 15 mg",
        form: "Tablets",
      },
      {
        id: 39,
        name: "Ketorolac Sublingual Tablets",
        strength: "20 mg",
        form: "Tablets",
      },
      {
        id: 40,
        name: "Ketorolac Sublingual Tablets",
        strength: "30 mg",
        form: "Tablets",
      },
      {
        id: 41,
        name: "Paracetamol Infusion",
        strength: "1% w/v",
        form: "Infusion",
      },
      {
        id: 42,
        name: "Orphenadrine Citrate + Paracetamol Tablets BP",
        strength: "35 mg + 450 mg",
        form: "Tablets",
      },
      {
        id: 43,
        name: "Diclofenac Diethylamine + Linseed Oil + Menthol + Methyl Salicylate Gel",
        strength: "N/A",
        form: "Gel",
      },
      {
        id: 44,
        name: "Ketorolac Sublingual Tablets",
        strength: "20 mg",
        form: "Tablets",
      },
      {
        id: 45,
        name: "Ketorolac Sublingual Tablets",
        strength: "30 mg",
        form: "Tablets",
      },
      {
        id: 46,
        name: "Ketorolac Tromethamine Injection USP",
        strength: "30 mg/ml",
        form: "Injection",
      },
      {
        id: 47,
        name: "Orphenadrine Citrate + Paracetamol Tablets",
        strength: "650 mg",
        form: "Tablets",
      },
      {
        id: 48,
        name: "Nitrofurantoin Tablets USP",
        strength: "100 mg",
        form: "Tablets",
      },
      {
        id: 49,
        name: "Deflazacort Tablets",
        strength: "6 mg",
        form: "Tablets",
      },
      {
        id: 50,
        name: "Diclofenac Sodium Injection",
        strength: "3 ml",
        form: "Injection",
      },
      {
        id: 51,
        name: "Etoricoxib Tablets",
        strength: "60 mg, 90 mg",
        form: "Tablets",
      },
      {
        id: 52,
        name: "Serratiopeptidase Tablets",
        strength: "10 mg",
        form: "Tablets",
      },
      {
        id: 53,
        name: "Dexamethasone Tablets BP",
        strength: "0.5 mg",
        form: "Tablets",
      },
      {
        id: 54,
        name: "Ibuprofen Tablets USP",
        strength: "400 mg",
        form: "Tablets",
      },
      {
        id: 55,
        name: "Leflunomide Tablets BP",
        strength: "10 mg",
        form: "Tablets",
      },
      {
        id: 56,
        name: "Leflunomide Tablets BP",
        strength: "20 mg",
        form: "Tablets",
      },
      {
        id: 57,
        name: "Celecoxib Capsules BP",
        strength: "100 mg",
        form: "Capsules",
      },
      {
        id: 58,
        name: "Celecoxib Capsules BP",
        strength: "200 mg",
        form: "Capsules",
      },
    ],
  },
  {
    title: "Food Supplements And Nutraceutical Products",
    slug: "food-supplements-nutraceutical-products",
    bannerImages: [CalciumCarbonateTabletsUSPImage],
    products: [
      {
        id: 1,
        name: "Ferrous Fumarate, Folic Acid and Vitamin B 12 Capsules",
        strength: "200 mg + 1 mg + 10 mcg",
        form: "Capsules",
      },
      {
        id: 2,
        name: "Ferrous Sulphate and Folic Acid Tablets",
        strength: "90 mg + 1 mg",
        form: "Tablets",
      },
      {
        id: 3,
        name: "Haematinic Capsules",
        strength: "60 mg + 3 mg + 1.5 mg + 15 mcg",
        form: "Capsules",
      },
      {
        id: 4,
        name: "Pyridoxine Tablets BP",
        strength: "50mg",
        form: "Tablets",
      },
      { id: 5, name: "Riboflavin Tablets", strength: "5mg", form: "Tablets" },
      {
        id: 6,
        name: "Vitamin C Tablets BP",
        strength: "100mg",
        form: "Tablets",
      },
      {
        id: 7,
        name: "Vitamin C Chewable Tablets BP",
        strength: "500mg",
        form: "Tablets",
      },
      {
        id: 8,
        name: "Vitamin C and Glucose Tablets",
        strength: "50mg+150mg",
        form: "Tablets",
      },
      {
        id: 9,
        name: "Zinc Sulphate Dispersible Tablets",
        strength: "20mg",
        form: "Tablets",
      },
      {
        id: 10,
        name: "Calcium Carbonate Tablets USP",
        strength: "500 mg",
        form: "Tablets",
      },

      {
        id: 11,
        name: "Oral Rehydration Salts with Zinc",
        strength: "20 gm + 3.5 gm + 2.9 gm + 1.5 gm + 10 mg",
        form: "N/A",
      },
      {
        id: 12,
        name: "Oral Rehydration Salts Sachet BP",
        strength: "3.50 gm + 1.5 gm + 2.90 gm + 20 gm",
        form: "N/A",
      },
      {
        id: 13,
        name: "Salt and Dextrose Tablets",
        strength: "300 mg + 200 mg",
        form: "N/A",
      },

      {
        id: 14,
        name: "Multivitamin Multimineral Antioxidant with Ginseng Capsules",
        strength: "Full Composition",
        form: "Hard Gel Capsules",
      },
      {
        id: 15,
        name: "Lycopene with DHA Capsules",
        strength: "Full Composition",
        form: "Hard Gel Capsules",
      },
      {
        id: 16,
        name: "B-Complex with Lactic acid bacillus and Zinc Capsules",
        strength: "Full Composition",
        form: "Hard Gel Capsules",
      },
      {
        id: 17,
        name: "Betacarotene, Lutein, Vit E, Riboflavin, Vit B1 and trace elements capsules",
        strength: "Full Composition",
        form: "Hard Gel Capsules",
      },
      {
        id: 18,
        name: "Lycopene with Vit A Vit C and Vit E Capsules",
        strength: "Full Composition",
        form: "Hard Gel Capsules",
      },
      {
        id: 19,
        name: "Green Tea Extract, Lycopene, Vit C, Vit E, Pyridoxine, Folic Acid, Methylcobalamin with Selenium capsules",
        strength: "Full Composition",
        form: "Hard Gel Capsules",
      },
      {
        id: 20,
        name: "Soya Isoflavone, Green Tea Extract, Omega 3 fatty acid, Biotin, Vit D3 with Selenium capsules",
        strength: "Full Composition",
        form: "Hard Gel Capsules",
      },

      {
        id: 21,
        name: "Prebiotic Probiotic Capsules",
        strength: "Full Composition",
        form: "Hard Gel Capsules",
      },
      {
        id: 22,
        name: "Multivitamin Multimineral Antioxidant Capsules with Lycopene",
        strength: "Full Composition",
        form: "Hard Gel Capsules",
      },

      {
        id: 23,
        name: "Energy Enhancer",
        strength: "Full Composition",
        form: "Powder",
      },
      {
        id: 24,
        name: "Protein Powder with DHA & Lycopene",
        strength: "Full Composition",
        form: "Powder",
      },
      {
        id: 25,
        name: "Protein Powder 1",
        strength: "Full Composition",
        form: "Powder",
      },
      {
        id: 26,
        name: "Protein Powder fortified with vitamins and minerals",
        strength: "Full Composition",
        form: "Powder",
      },
      {
        id: 27,
        name: "Protein Powder fortified with vitamins and minerals",
        strength: "Full Composition",
        form: "N/A",
      },

      {
        id: 28,
        name: "L-Ornithine L-Aspartate Sachet",
        strength: "3 gm",
        form: "Sachets",
      },
      {
        id: 29,
        name: "D-Mannose and Cranberry Extract Sachet (For UTI)",
        strength: "Full Composition",
        form: "Sachets",
      },
      {
        id: 30,
        name: "Bioactive Collagen peptide sachet",
        strength: "10 gm",
        form: "Sachets",
      },
      {
        id: 31,
        name: "Bioactive Collagen peptide with Glucosamine and Vit C sachet",
        strength: "Full Composition",
        form: "Sachets",
      },
      {
        id: 32,
        name: "L-Arginine with zinc and folic acid sachet",
        strength: "Full Composition",
        form: "Sachets",
      },
      {
        id: 33,
        name: "L-Arginine with proanthocyanidin sachet",
        strength: "Full Composition",
        form: "Sachets",
      },
      { id: 34, name: "L-Arginine Sachet", strength: "3 gm", form: "Sachets" },
      {
        id: 35,
        name: "L-Arginine, Methylcobalamin, Folic Acid and Zinc Sachets",
        strength: "Full Composition",
        form: "Sachets",
      },
      {
        id: 36,
        name: "Prebiotic Probiotic Sachet",
        strength: "Full Composition",
        form: "Sachets",
      },

      {
        id: 37,
        name: "Calcium, Zinc, Vit K2-7, Methylcobalamin and L-Methyl Folate Soft Gel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },
      {
        id: 38,
        name: "Omega 3 fatty acid, Calcium Carbonate, Folic Acid, Vit B12 and Boron Soft Gel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },
      {
        id: 39,
        name: "Omega 369 Soft Gelatin Capsules",
        strength: "Omega 369 (150 mg)",
        form: "Soft Gel Capsules",
      },
      {
        id: 40,
        name: "Omega 3 fatty acid, Co-Enzyme Q10, L Arginine and Selenium soft gel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },
      {
        id: 41,
        name: "Omega 3 fatty acid, Co-Enzyme Q10, Zinc, Folic Acid and Selenium soft gel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },
      {
        id: 42,
        name: "Omega 3 fatty acid, Co-Enzyme Q10, Multivitamin and Multimineral soft gel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },

      {
        id: 43,
        name: "Omega 369 Soft Gelatin Capsules",
        strength: "Evening Primrose Oil (500 mg) + Cod liver oil (300 mg)",
        form: "Soft Gel Capsules",
      },
      {
        id: 44,
        name: "Omega 3 fatty acids, Green Tea Extract, Ginko Biloba Extract, Ginseng, Grape Seed Extract, Antioxidants, Vitamins, Minerals & Trace Elements Softgel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsule",
      },
      {
        id: 45,
        name: "Omega 3 fatty acid, Asthaxanthin, Lutein, Zeaxanthin, Beta carotene, Multivitamin and Multiminerals soft gel capsule",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },

      {
        id: 46,
        name: "Cod Liver Oil with Vit A and vit E soft gel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },
      {
        id: 47,
        name: "Curcumin with Piperine Soft Gel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },
      {
        id: 48,
        name: "Lutein, Lycopene, Grape Seed, B complex and selenium Soft Gel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },
      {
        id: 49,
        name: "Grape Seed Extract, Green Tea Extract, Beta carotene, Lutein, Lycopene, Multivitamin and Multimineral soft gel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },

      {
        id: 50,
        name: "Evening Primrose Oil Soft Gel Capsules",
        strength: "500/1000mg",
        form: "Soft Gel Capsules",
      },
      {
        id: 51,
        name: "Wheat Germ Oil Soft Gel Capsules",
        strength: "400 mg",
        form: "Soft Gel Capsules",
      },
      {
        id: 52,
        name: "Evening Primrose Oil and Tocotrienols Soft Gel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },
      {
        id: 53,
        name: "Evening Primrose Oil and Vit E Soft Gel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },

      {
        id: 54,
        name: "Omega 3 fatty acids, Green Tea Extract, Ginko Biloba Extract, Ginseng, Grape Seed Extract, Ginger Root Extract, Garlic, Antioxidants, Vitamins, Minerals Trace Elements Softgel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsules",
      },
      {
        id: 55,
        name: "Omega 3 fatty acids, Green Tea Extract, Ginko Biloba Extract, Ginseng, Grape Seed Extract, Ginger Root Extract, Garlic, Glycyrrhiza Glabra, Green Coffee Bean Extract, Guggul, Antioxidants, Vitamins, Minerals & Trace Elements Softgel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsulse",
      },

      {
        id: 56,
        name: "Alpha Ketoanalogue of Essential Amino Acid Tablets",
        strength: "Full Composition",
        form: "Tablets",
      },
      {
        id: 57,
        name: "B-Complex with Folic acid & L-Lysine Tablets",
        strength: "Full Composition",
        form: "Tablets",
      },
      {
        id: 58,
        name: "Calcium Fortified with Zinc, Lysine and Vitamin D3 Suspension",
        strength: "Full Composition",
        form: "Suspension",
      },
      {
        id: 59,
        name: "Co-enzyme-Q 10, EPA and DHA, Lycopene, Selenium soft geletin capsules",
        strength: "Full Composition",
        form: "Soft Geletin Capsule",
      },
      {
        id: 60,
        name: "Multivitamin and Multiminerals with Anti oxidants Soft gel Capsules",
        strength: "Full Composition",
        form: "Soft Geletin Capsule",
      },
      {
        id: 61,
        name: "Multivitamin with Zinc and Chromium Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsule",
      },
      {
        id: 62,
        name: "Flaxseed oil containing omega 3,6 and 9 Fatty acids Softgel Capsules",
        strength: "Full Composition",
        form: "Soft Gel Capsule",
      },
    ],
  },
]
